baseURL = "https://blacksmithop.github.io/blacksmithop/"
title = "Abhinav KM"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true


[params]
author = "Abhinav KM"
description = "Abhinav's personal website"
keywords = "blog,developer,personal"
info = ["Python Developer"]
avatarURL = "images/abhi-cover.webp"

dateFormat = "April 1, 2022"
since = 2022

enableRobotsTXT = true

rtl = false

colorScheme = "dark"

hideColorSchemeToggle = false

maxSeeAlsoItems = 5

customCSS = []
customSCSS = []
customJS = []

[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = [
  "'self'", 
  "'unsafe-inline'", 
  "https://www.google-analytics.com",
  "https://cdn.jsdelivr.net/"
]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/blacksmithop/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-2x fa-gitlab"
weight = 2
url = "https://gitlab.com/users/blacksmithop/projects/"

[[params.social]]
name = "Bitbucket"
icon = "fa fa-2x fa-bitbucket"
weight = 2
url = "https://bitbucket.org/BlackSmithOP/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/abhinav--km/"

[[params.social]]
name = "Medium"
icon = "fa fa-2x fa-medium"
weight = 5
url = "https://medium.com/@angstycoder101/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Projects"
weight = 1
url = "projects/"

