name: Create PR when a new branch is pushed
on:
  push:
    branches-ignore:
      - main
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches and history
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Get commit messages
        id: commit_messages
        shell: bash
        run: |
          commits=$(git log origin/main..${{ steps.extract_branch.outputs.branch }} --pretty=format:"%s")
          echo "commits=$commits" >> $GITHUB_OUTPUT
      - name: Create PR
        uses: blacksmithop/create-pr-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          BASE_BRANCH: main
          TITLE: Merge ${{ steps.extract_branch.outputs.branch }} with main
          BODY: |
            Changes:
            ${{ steps.commit_messages.outputs.commits }}
