name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/react-gh-pages-deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/react-gh-pages-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Install dependencies
        run: pnpm install
        working-directory: ./frontend
      
      - name: Build
        run: pnpm run build
        working-directory: ./frontend
      
      - name: Verify build output
        run: |
          echo "Checking build output directory..."
          ls -la
          if [ -d "out" ]; then
            echo "✓ out directory exists"
            ls -la out/
          elif [ -d ".next" ]; then
            echo "✓ .next directory exists"
            ls -la .next/
          elif [ -d "dist" ]; then
            echo "✓ dist directory exists"
            ls -la dist/
          else
            echo "❌ No standard build directory found"
            echo "Available directories:"
            find . -maxdepth 2 -type d -name "*build*" -o -name "*out*" -o -name "*dist*" -o -name "*.next*"
          fi
        working-directory: ./frontend
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/out
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
